version: 2
registries:
  aplanatic-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.APLANATIC_PACKAGES_TOKEN }}
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    registries: [aplanatic-packages]
    open-pull-requests-limit: 5
