version: 2
registries:
  aplanatic-github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.APLANATIC_REPO_TOKEN }}
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    registries: [aplanatic-github]
    open-pull-requests-limit: 5
